<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\OAuth2Client;

use Fisharebest\Webtrees\Http\RequestHandlers\HomePage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\User;
use Jefferson49\Webtrees\Module\OAuth2Client\Factories\AuthorizationProviderFactory;
use Jefferson49\Webtrees\Module\OAuth2Client\LoginWithAuthorizationProviderAction;


/**
 * @var Tree|null $tree
 * @var string    $url
 * @var User      $user
 * @var string    $connect_action
 */

$user = $user ?? null;
$connect_action = $connect_action ?? OAuth2Client::CONNECT_ACTION_NONE;
$url = $url ?? route(HomePage::class);
$sign_in_button_labels = AuthorizationProviderFactory::getSignInButtonLables();
$provider_of_user = $user !== null ? $user->getPreference(OAuth2Client::USER_PREF_PROVIDER_NAME, '') : '';

?>

<?php if (sizeof($sign_in_button_labels) > 0) : ?>
    <div class="wt-page-options wt-page-options-login">
        <div class="row mb-3">
    <label class="col-sm-3 col-form-label wt-page-options-label">
                <?php if ($connect_action === OAuth2Client::CONNECT_ACTION_CONNECT) : ?>
                    <?= I18N::translate('Connect with') ?>                    
                <?php elseif ($connect_action === OAuth2Client::CONNECT_ACTION_DISCONNECT) : ?>
                    <?= I18N::translate('Disconnect from') ?>
                <?php elseif ($connect_action === OAuth2Client::CONNECT_ACTION_NONE) : ?>
                    <?= I18N::translate('Sign in with') ?>
                <?php endif ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <form method="post">
                    <?php foreach ($sign_in_button_labels as $provider_name => $sign_in_button_label) : ?>
                        <?php if($connect_action !== OAuth2Client::CONNECT_ACTION_DISCONNECT OR $provider_name === $provider_of_user) : ?>
                            <a href="<?= e(route(LoginWithAuthorizationProviderAction::class, [
                                'tree'            => $tree instanceof Tree ? $tree->name() : null,
                                'url'             => $url,
                                'provider_name'   => $provider_name,
                                'user'            => $user !== null ? $user->id() : 0,
                                'connect_action'  => $connect_action,
                            ])) ?>" type="submit" class="btn btn-secondary">
                            <?= $sign_in_button_label ?>
                            </a>
                        <?php endif ?>
                    <?php endforeach ?>
                    <?= csrf_field() ?>
                </form>
            </div>
        </div>
    </div>
<?php endif ?>
